### ISSUE TITLE
StyleCop is introducing warnings

### ISSUE THREAD

**Issue by underscoreHao** [donnytian/IpSet#1]
Hi,

I've been using your package for some work I needed done last few days and I really like it. However there's an annoying behavior introduced by StyleCop. All of my projects are using tabs, not spaces, and every line with tabs is being flagged as a warning.

A .editorconfig file is a cleaner way to do the same I think :) I was thinking of doing a PR removing the StyleCop stuff or adding this line to **GlobalSuppresions.cs**

```csharp
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1027:Tabs must not be used", Justification = "Reviewed.")]
```

Would that be ok? Thanks!

**Comment by atlassanjay** [comment]
Agreed, i'm trying to use this lib but don't want style cop at all.

**Comment by underscoreHao** [comment]
@donnytian Another option would be to put StyleCop's dependency in your project as a PrivateAsset

https://docs.microsoft.com/en-us/dotnet/core/tools/csproj#includeassets-excludeassets-and-privateassets

**Comment by donnytian** [comment]
hi, sorry for the late response.
I upgrade the SytleCop to the latest version and it automatically added below content to csproj file, seems it is exactly what you suggested about `PrivateAsset`.
Hope this will work for you guys. Let me know please.

Thanks for your contribution!

**Comment by underscoreHao** [comment]
@donnytian Thanks for the update, but even after the update I still have the same warnings.

![image](https://user-images.githubusercontent.com/5088351/62870179-140cfd00-bd11-11e9-88af-0acf4c2953ab.png)

**Comment by donnytian** [comment]
Hi, I think finally I resolved this issue. Please verify on `v0.1.1` and let me know. Thanks!

**Comment by PavelDanov** [comment]
@donnytian `v0.1.1` fixed my issue 🎉🥳 谢谢你！
